### ISSUE TITLE
Having issues when extracting macOS dyld

### ISSUE THREAD

**Issue by dimitarnestorov** [blacktop/ipsw#96]
Doesn't work when specifying an arch:
```
dimitarnestorov@Dimitars-MacBook-Pro /t/ipsw> ./ipsw extract -d UniversalMac_12.3_21E230_Restore.ipsw --dyld-arch arm64e
   • Extracting dyld_shared_cache
      • Created 018-25400-286.dmg
      • Mounting DMG
      • Unmounting DMG
   ⨯ failed to extract dyld_shared_cache: no dyld_shared_cache files found matching the specified archs: [arm64e]
dimitarnestorov@Dimitars-MacBook-Pro /t/ipsw [1]> ./ipsw extract -d UniversalMac_12.3_21E230_Restore.ipsw --dyld-arch x86_64
   • Extracting dyld_shared_cache
      • Created 018-25400-286.dmg
      • Mounting DMG
      • Unmounting DMG
   ⨯ failed to extract dyld_shared_cache: no dyld_shared_cache files found matching the specified archs: [x86_64]
```

Doesn't work without `--dyld-arch`
```
dimitarnestorov@Dimitars-MacBook-Pro /t/ipsw [1]> ./ipsw extract -d UniversalMac_12.3_21E230_Restore.ipsw
   • Extracting dyld_shared_cache
      • Created 018-25400-286.dmg
      • Mounting DMG
? Which files would you like to extract: ✅
         • Extracting dyld_shared_cache_arm64e to 21E230__Mac13,1_2_MacBookAir10,1_MacBookPro17,1_MacBookPro18,1_2_3_4_Macmini9,1_VirtualMac2,1_iMac21,1_2/dyld_shared_cache_arm64e
         • Extracting dyld_shared_cache_arm64e.1 to 21E230__Mac13,1_2_MacBookAir10,1_MacBookPro17,1_MacBookPro18,1_2_3_4_Macmini9,1_VirtualMac2,1_iMac21,1_2/dyld_shared_cache_arm64e.1
         • Extracting dyld_shared_cache_arm64e.map to 21E230__Mac13,1_2_MacBookAir10,1_MacBookPro17,1_MacBookPro18,1_2_3_4_Macmini9,1_VirtualMac2,1_iMac21,1_2/dyld_shared_cache_arm64e.map
         • Extracting dyld_shared_cache_x86_64 to 21E230__Mac13,1_2_MacBookAir10,1_MacBookPro17,1_MacBookPro18,1_2_3_4_Macmini9,1_VirtualMac2,1_iMac21,1_2/dyld_shared_cache_x86_64
         • Extracting dyld_shared_cache_x86_64.1 to 21E230__Mac13,1_2_MacBookAir10,1_MacBookPro17,1_MacBookPro18,1_2_3_4_Macmini9,1_VirtualMac2,1_iMac21,1_2/dyld_shared_cache_x86_64.1
         • Extracting dyld_shared_cache_x86_64.2 to 21E230__Mac13,1_2_MacBookAir10,1_MacBookPro17,1_MacBookPro18,1_2_3_4_Macmini9,1_VirtualMac2,1_iMac21,1_2/dyld_shared_cache_x86_64.2
         • Extracting dyld_shared_cache_x86_64.3 to 21E230__Mac13,1_2_MacBookAir10,1_MacBookPro17,1_MacBookPro18,1_2_3_4_Macmini9,1_VirtualMac2,1_iMac21,1_2/dyld_shared_cache_x86_64.3
         • Extracting dyld_shared_cache_x86_64.map to 21E230__Mac13,1_2_MacBookAir10,1_MacBookPro17,1_MacBookPro18,1_2_3_4_Macmini9,1_VirtualMac2,1_iMac21,1_2/dyld_shared_cache_x86_64.map
         • Extracting dyld_shared_cache_x86_64h to 21E230__Mac13,1_2_MacBookAir10,1_MacBookPro17,1_MacBookPro18,1_2_3_4_Macmini9,1_VirtualMac2,1_iMac21,1_2/dyld_shared_cache_x86_64h
         • Extracting dyld_shared_cache_x86_64h.1 to 21E230__Mac13,1_2_MacBookAir10,1_MacBookPro17,1_MacBookPro18,1_2_3_4_Macmini9,1_VirtualMac2,1_iMac21,1_2/dyld_shared_cache_x86_64h.1
         • Extracting dyld_shared_cache_x86_64h.2 to 21E230__Mac13,1_2_MacBookAir10,1_MacBookPro17,1_MacBookPro18,1_2_3_4_Macmini9,1_VirtualMac2,1_iMac21,1_2/dyld_shared_cache_x86_64h.2
         • Extracting dyld_shared_cache_x86_64h.3 to 21E230__Mac13,1_2_MacBookAir10,1_MacBookPro17,1_MacBookPro18,1_2_3_4_Macmini9,1_VirtualMac2,1_iMac21,1_2/dyld_shared_cache_x86_64h.3
         • Extracting dyld_shared_cache_x86_64h.map to 21E230__Mac13,1_2_MacBookAir10,1_MacBookPro17,1_MacBookPro18,1_2_3_4_Macmini9,1_VirtualMac2,1_iMac21,1_2/dyld_shared_cache_x86_64h.map
         • Extracting dyld_shared_cache_arm64e to 21E230__Mac13,1_2_MacBookAir10,1_MacBookPro17,1_MacBookPro18,1_2_3_4_Macmini9,1_VirtualMac2,1_iMac21,1_2/dyld_shared_cache_arm64e
      • Unmounting DMG
   ⨯ failed to extract dyld_shared_cache: open dyld_shared_cache_arm64e: no such file or directory
``` 

Also doesn't matter which files I choose when not using `--dyld-arch`. It always extracts everything and fails.

Same issues when trying with both macOS 11.0.1 and 12.3.

Version:  3.1.90

**Comment by blacktop** [comment]
Many thanks for letting me know!

**Comment by blacktop** [comment]
should be fixed now

**Comment by dimitarnestorov** [comment]
When using `--dyld-arch` argument it works fine but when you pick files it still fails:

https://user-images.githubusercontent.com/8790386/160772515-3f2e349c-1ca4-4099-9841-d4f942afe2af.mp4

**Comment by dimitarnestorov** [comment]
`--output` doesn't seem to work at all

**Comment by blacktop** [comment]
both 🆕 issues should be fixed now.  Once again I greatly appreciate you letting me know!  I had no idea this functionality was so broken 😞

**Comment by dimitarnestorov** [comment]
Thank you for handling these issues so quickly! Just tested with the new version and I can confirm that they were fixed. For me those weren't mission critical. It's just some stuff I noticed while messing around with your awesome tool.
